services:

  myflask:
    image: myflask:v1.0.0
    build: ./backend
    ports:
      - 8080:8080
    environment:
      MONGODB_HOST: mongo
    networks:
      - E-shop

  mongo:
    image: mongo:8.0
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - E-shop

  mongo-express:
    image: mongo-express:1-20-alpine3.19
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
    networks:
      - E-shop

  webserver:
    image: frontend:1.0
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: webserver
    ports:
      - 80:80
    networks:
      - E-shop
    depends_on:
      - myflask
    volumes:
    - ./frontend:/usr/share/nginx/html
    - ./frontend/nginx.conf:/etc/nginx/nginx.conf
    - ./README.md:/usr/share/nginx/html/README.md

networks:
  E-shop:
    driver: bridge
